import { ConfigService } from '@nestjs/config';
import { ServiceNowService } from '../servicenow/servicenow.service';
import { ConnectorConfigService } from '../connector-config.service';
import { DirectTicketProvider } from './direct-ticket.provider';
import { N8nTicketProvider } from './n8n-ticket.provider';
import { TicketUpdateOutcome } from './ticket-update.provider';

/**
 * W40 F5 — the seam ④ contract: the same situation, both providers, the same
 * result.
 *
 * Each case is arranged TWICE — once in ServiceNow's language (a Table API
 * response) and once in n8n's (a webhook body). Making those two arrangements
 * mean the same thing is the actual work here, and it is the only place a
 * mistranslation can hide: everything else about the two implementations is
 * covered by their own specs.
 *
 * 🔴 What this deliberately does NOT assert:
 *
 * 1. THE NOTE TEXT. Workflow 2004 appends "Handled & generated by n8n." to
 *    anything that does not already say so, and truncates at 3900 characters.
 *    That is deliberate on their side and useful on ours — the ticket shows
 *    which path wrote it — so requiring the two to write identical text would
 *    be requiring the wrong thing (W40 OQ-C). The contract is WHERE THE TICKET
 *    ENDS UP.
 *
 * 2. THE ERROR MESSAGE. When something is down, whoever is on call needs to
 *    know WHICH thing is down, so "ServiceNow" and "n8n is unavailable" must
 *    differ. The contract is the failure CLASS, not the wording.
 *
 * 3. THE REFUSAL SHAPE — and that one is a real asymmetry, pinned separately
 *    below rather than smoothed over.
 */
describe('ticket-update seam contract (both providers, same outcome)', () => {
  let snow: { updateRecord: jest.Mock };
  let fetchMock: jest.Mock;
  let direct: DirectTicketProvider;
  let n8n: N8nTicketProvider;

  beforeEach(() => {
    snow = { updateRecord: jest.fn() };
    direct = new DirectTicketProvider(snow as unknown as ServiceNowService);

    fetchMock = jest.fn();
    global.fetch = fetchMock as unknown as typeof fetch;
    n8n = new N8nTicketProvider(
      { get: () => 'key' } as unknown as ConfigService,
      {
        resolve: async () => 'https://n8n.example.com/webhook',
      } as unknown as ConnectorConfigService,
    );
  });

  /** The Table API echoes the patched record back. */
  const serviceNowSays = (state: string | undefined) =>
    snow.updateRecord.mockResolvedValue(state === undefined ? {} : { state });

  /** 2004 answers 200 with its Build Response body. */
  const n8nSays = (body: Record<string, unknown>) =>
    fetchMock.mockResolvedValue({
      ok: true,
      status: 200,
      json: async () => body,
    } as Response);

  describe.each([
    {
      what: 'a completed line item is closed',
      call: (p: DirectTicketProvider | N8nTicketProvider) =>
        p.closeComplete('RITM1', 'License E3 assigned via platform.'),
      arrangeDirect: () => serviceNowSays('3'),
      arrangeN8n: () => n8nSays({ status: 'success', newState: '3' }),
      expected: { status: 'updated', newState: '3' } as TicketUpdateOutcome,
    },
    {
      what: 'a blocked line item is put on hold',
      call: (p: DirectTicketProvider | N8nTicketProvider) =>
        p.markInProgress('RITM1', 'Procurement in progress.'),
      arrangeDirect: () => serviceNowSays('2'),
      arrangeN8n: () => n8nSays({ status: 'success', newState: '2' }),
      expected: { status: 'updated', newState: '2' } as TicketUpdateOutcome,
    },
    {
      /**
       * Neither system promises to echo the field back. Both must then report
       * the state we asked for rather than null — telling the caller "unknown"
       * about a patch that just succeeded would be strictly worse information.
       */
      what: 'the ticket moved but no state came back',
      call: (p: DirectTicketProvider | N8nTicketProvider) =>
        p.closeComplete('RITM1', 'n'),
      arrangeDirect: () => serviceNowSays(undefined),
      arrangeN8n: () => n8nSays({ status: 'success' }),
      expected: { status: 'updated', newState: '3' } as TicketUpdateOutcome,
    },
  ])('$what', ({ call, arrangeDirect, arrangeN8n, expected }) => {
    it('direct reaches that outcome', async () => {
      arrangeDirect();
      await expect(call(direct)).resolves.toEqual(expected);
    });

    it('n8n reaches the same outcome', async () => {
      arrangeN8n();
      await expect(call(n8n)).resolves.toEqual(expected);
    });
  });

  /**
   * The vendor being unreachable is the absence of an outcome, not one of its
   * values — both providers throw. The MESSAGES differ on purpose (see the
   * header), so only the class is asserted.
   */
  describe('the vendor is unreachable', () => {
    it('direct lets the failure through instead of reporting an outcome', async () => {
      snow.updateRecord.mockRejectedValue(new Error('ServiceNow down'));
      await expect(direct.closeComplete('RITM1', 'n')).rejects.toThrow();
    });

    it('n8n also throws rather than reporting an outcome', async () => {
      fetchMock.mockRejectedValue(new Error('ECONNREFUSED'));
      await expect(n8n.closeComplete('RITM1', 'n')).rejects.toThrow();
    });
  });

  /**
   * 🔴 A REAL ASYMMETRY — pinned, not smoothed over.
   *
   * When ServiceNow refuses the PATCH the two paths cannot answer the same way,
   * and it is not a missing mapping:
   *
   *   direct  ServiceNowService throws on any non-2xx → the caller gets an
   *           exception.
   *   n8n     2004 patches with `neverError: true`, so the webhook answers 200
   *           and reports the refusal in its body → the caller gets an `error`
   *           outcome.
   *
   * Both are correct for their transport. What matters — and what IS asserted —
   * is that neither one can be mistaken for success, because reporting a ticket
   * as closed while it never moved is the failure mode this seam must not have.
   *
   * If someone later "harmonises" these (making the n8n side throw, or the
   * direct side swallow), this test goes red and sends them back here first.
   */
  describe('ServiceNow refuses the patch', () => {
    it('direct surfaces it as a thrown failure', async () => {
      snow.updateRecord.mockRejectedValue(
        new Error('ServiceNow request failed (403)'),
      );
      await expect(direct.closeComplete('RITM1', 'n')).rejects.toThrow();
    });

    it('n8n surfaces it as an error outcome — never as updated', async () => {
      n8nSays({ status: 'error', httpStatus: 403, details: 'ACL' });

      const outcome = await n8n.closeComplete('RITM1', 'n');

      expect(outcome.status).toBe('error');
    });
  });

  /**
   * Negative half: each provider reaches its own system and only its own. A
   * direct call that quietly went through the webhook (or the reverse) would
   * still produce the right outcome in every test above.
   */
  describe('each provider reaches only its own system', () => {
    it('direct never calls the webhook', async () => {
      serviceNowSays('3');
      await direct.closeComplete('RITM1', 'n');
      expect(fetchMock).not.toHaveBeenCalled();
    });

    it('n8n never touches the Table API', async () => {
      n8nSays({ status: 'success', newState: '3' });
      await n8n.closeComplete('RITM1', 'n');
      expect(snow.updateRecord).not.toHaveBeenCalled();
    });

    /**
     * Both address the same RITM, each in the only way its transport allows.
     *
     * The table is NOT symmetric to assert: the direct side names it, while on
     * the n8n side it is inside 2004's own patch URL and the platform never
     * sends it. So this asserts what each side actually controls — naming the
     * table where we can, and naming the RITM + mode where we cannot.
     */
    it('direct names sc_req_item; n8n names the RITM and the mode', async () => {
      serviceNowSays('3');
      await direct.closeComplete('RITM1', 'n');
      expect(snow.updateRecord).toHaveBeenCalledWith(
        'RITM1',
        expect.anything(),
        'sc_req_item',
      );

      n8nSays({ status: 'success', newState: '3' });
      await n8n.closeComplete('RITM1', 'n');
      expect(JSON.parse(fetchMock.mock.calls[0][1].body)).toEqual(
        expect.objectContaining({ ritmId: 'RITM1', mode: 0 }),
      );
    });
  });
});
